### PR TITLE
Fix policy as a map causing RuntimeException

### PR DESCRIPTION
**Pull request by jacobemcken**
Exception:

    Caused by: java.lang.RuntimeException: Unable to resolve symbol: update in this context

### CODE REVIEW

**Comment by pyr** [comment]
Hi @jacobemcken,

This isn't valid unfortunately, it will just make the key be the `keyword` function, not apply it on a previous value.

**Comment by pyr** [comment]
What you want here is a third argument for `format-policy` which is used as a default type

**Comment by pyr** [comment]
@jacobemcken are you willing to update the PR ?

**Comment by jacobemcken** [comment]
I don't know what I was thinking when I set the type to the function `keyword` :open_mouth: must have been late :smile:

TBH I'm not sure how to properly fix this due my limited experience with logging in general and how unilog is supposed to work (just copy pasted some code an noticed an exception).

Ie. in which use cases would `build-appender` usually receive a keyword, a string and a map as `policy`. I think I'm missing some context to understand the problem that needs solving.

I don't understand why a default type is needed when a `type` is always provided to the anonymous function saved in `format-policy`... wouldn't it always be overwritten?

If you have a bit more info I willing to give a try, but then again I just might be the wrong person for the job :smile:

**Comment by cedrictools** [comment]
Isn't this just a confict due to clojure version ?
`clojure.core/update` is only available since version 1.7.0
The error you're reporting might happen if you're use [clojure 1.6.0] or older in your project.clj.
See the lein command `lein deps :tree` for tracking version conflict.
```
[clojure/clojure  "1.6.0"]
 overrides
[spootnik/unilog  "0.7.10"] ->  [org.clojure/clojure  "1.7.0"]
```
If that happen to be the case, then the fix is not to use `assoc` but `update-in`

**Comment by pyr** [comment]
HI @cedrictools,

Thanks for reviving this thread, I had forgotten about it.
This is the most likely culprit, I've just fixed it in master and pushed and updated version as 0.7.12

**Pull request closed without merging**
